export const STRAIGHT_LINE_SIZE_DIVISOR = 8;
export const STRAIGHT_LINE_POSITION_PADDING = 0.45;
export const DIAGONAL_LINE_SIZE_DIVISOR = 10;
export const DIAGONAL_LINE_ANGLE = 45;
export const DIAGONAL_LINE_LENGTH_SIZE_PADDING = 50;
